// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2zPTZfhkyPdLbV54SaAmnB_m0yKpvTK0',
    appId: '1:866253613907:web:a4e542daf8f501d92e0fa6',
    messagingSenderId: '866253613907',
    projectId: 'alarmcare-3eb10',
    authDomain: 'alarmcare-3eb10.firebaseapp.com',
    storageBucket: 'alarmcare-3eb10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wds6Y0nUzzSrf6lOhBzOSr0yBaZ8bcM',
    appId: '1:866253613907:android:dce4d50f3daddcd92e0fa6',
    messagingSenderId: '866253613907',
    projectId: 'alarmcare-3eb10',
    storageBucket: 'alarmcare-3eb10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvE_JBIDS_Y5lBtisMXcRdt-AcIX2RPIU',
    appId: '1:866253613907:ios:97b40b4fc225dff82e0fa6',
    messagingSenderId: '866253613907',
    projectId: 'alarmcare-3eb10',
    storageBucket: 'alarmcare-3eb10.firebasestorage.app',
    iosBundleId: 'com.example.NightSleepUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvE_JBIDS_Y5lBtisMXcRdt-AcIX2RPIU',
    appId: '1:866253613907:ios:97b40b4fc225dff82e0fa6',
    messagingSenderId: '866253613907',
    projectId: 'alarmcare-3eb10',
    storageBucket: 'alarmcare-3eb10.firebasestorage.app',
    iosBundleId: 'com.example.NightSleepUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2zPTZfhkyPdLbV54SaAmnB_m0yKpvTK0',
    appId: '1:866253613907:web:48d2d59e0a7f7a1c2e0fa6',
    messagingSenderId: '866253613907',
    projectId: 'alarmcare-3eb10',
    authDomain: 'alarmcare-3eb10.firebaseapp.com',
    storageBucket: 'alarmcare-3eb10.firebasestorage.app',
  );
}
